name: wnews
description: A tiny command-line newsreader backed by Wikipedia.
version: 0.1.1
repository: https://github.com/filiph/wnews

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.3.1
  xpath_selector: ^3.0.0
  xpath_selector_html_parser: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  wnews:
